name: Static code analysis

on: [ push ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: php-actions/composer@v6

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          path: src/
          level: 6
